/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        // Acctual Design Tokens
        ink: "#0f0f0f",
        hairline: "#d8d8d8",
        canvas: "#ffffff",
        "canvas-soft": "#fafafa",
        "muted-text": "#666",
        "muted-light": "#8d8d8d",
        "accent-blue": "#0098f2",
        "accent-pink": "#f200ca",
        "accent-purple": "#6c56fc",
        "accent-green": "#5d9c06",
        "accent-red": "#ff6363",
        "accent-orange": "#aa2d00",
      },
      borderRadius: {
        xs: "2px",
        sm: "6px",
        md: "10px",
        lg: "12px",
        xl: "16px",
        pill: "9999px",
        full: "9999px",
      },
      spacing: {
        xxs: "4px",
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
        section: "96px",
      },
      fontSize: {
        'hero': ['51px', { lineHeight: '1.05', fontWeight: '600' }],
        'hero-xl': ['69.2px', { lineHeight: '1.05', fontWeight: '600' }],
        'hero-sm': ['32.8px', { lineHeight: '1.1', fontWeight: '600' }],
        'hero-xs': ['21.8px', { lineHeight: '1.3', fontWeight: '500' }],
        'body-lg': ['19.1px', { lineHeight: '1.5', fontWeight: '400' }],
        'body': ['14.6px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm': ['12.7px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-sm': ['11.8px', { lineHeight: '1.3', fontWeight: '500' }],
        'label-xs': ['10px', { lineHeight: '1.2', fontWeight: '600' }],
        'display-xl': ['43.7px', { lineHeight: '1.1', fontWeight: '500' }],
        'display-lg': ['36.4px', { lineHeight: '1.2', fontWeight: '400' }],
        'display-md': ['29.1px', { lineHeight: '1.2', fontWeight: '400' }],
        'title-lg': ['21.8px', { lineHeight: '1.35', fontWeight: '400', letterSpacing: '0.12px' }],
        'title-md': ['18.2px', { lineHeight: '1.5', fontWeight: '400' }],
        'title-sm': ['16.4px', { lineHeight: '1.4', fontWeight: '500' }],
        'label-md': ['14.6px', { lineHeight: '1.4', fontWeight: '500' }],
        'body-md': ['12.7px', { lineHeight: '1.25', fontWeight: '400' }],
        'caption': ['12.7px', { lineHeight: '1.35', fontWeight: '500', letterSpacing: '0.16px' }],
        'legal': ['11.9px', { lineHeight: '1.2', fontWeight: '600' }],
        'pricing-display': ['40.8px', { lineHeight: '1.1', fontWeight: '475' }],
        'pricing-section': ['25.5px', { lineHeight: '1.2', fontWeight: '475' }],
        'pricing-card-title': ['18.2px', { lineHeight: '1.3', fontWeight: '475' }],
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
      },
      fontFamily: {
        heading: ['Geist Variable', 'Inter', 'system-ui', 'sans-serif'],
        body: ['Geist Variable', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['SF Mono', 'JetBrains Mono', 'monospace'],
        selecta: ['Selecta', 'sans-serif'],
        sfpro: ['SF Pro Display', 'sans-serif'],
        runde: ['Open Runde', 'sans-serif'],
        digital: ['Digital Numbers', 'sans-serif'],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "scroll-marquee": {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "scroll-marquee": "scroll-marquee 30s linear infinite",
        "fade-in-up": "fade-in-up 0.6s ease-out forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
